FROM node:20-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma

RUN npm install
RUN npx prisma generate

EXPOSE 3001
CMD ["npm", "run", "dev"]
